# Generated by Django 5.2.4 on 2025-08-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
