# Generated by Django 5.2.4 on 2025-08-05 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_profile_old_cart_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 8, 5, 12, 55, 24, 844023)),
        ),
    ]
